[devshell]
packages = ["nixpkgs-fmt", "julia_16-bin"]

[[commands]]
name = "pluto"
category = "Julia Package"
command = '''
        eval $(echo "nix develop --impure -c -- julia -L $$PRJ_ROOT/packages/julia/$1/startup.jl -e 'using Pluto; Pluto.run(host=\"$2\", port=$3)'")
        '''
help = "launch pluto server: pluto <juliaPackageDir> <ip> <port> | Example: pluto default 10.220.170.112 8889"


[[commands]]
name = "jupyterlab"
category = "jupyter"
command = '''
        set +u
        if [[ ! -z "$3" ]]; then
        sed -i "s|/packages/julia/.*.|/packages/julia/$3\"\)|" $PRJ_ROOT/nix/jupyterlab-env.nix
        else
        sed -i "s|/packages/julia/.*.|/packages/julia/default\"\)|" $PRJ_ROOT/nix/jupyterlab-env.nix
        fi
        nix develop .#jupyterlab-env --impure -c -- jupyter-lab --ip $1 --port $2 --config $PRJ_ROOT/jupyter_notebook_config.py
'''
help = "jupyterEnv <juliaPackageDir> <IP> <PORT> | Example: jupyterlab-env 10.220.170.112 8888 <Julia Activate DirName>"

[[commands]]
name = "juliaStartup"
category = "julia"
command = '''
        sed -i "s|/packages/julia/.*.|/packages/julia/$@\"\)|" $PRJ_ROOT/nix/jupyterlab-env.nix
        nix develop .#jupyterlab-env --impure --command -- juliaStartup
        '''
help = "juliaStartup <JuliaTutorial/default> | run julia with Startup.jl"


[[commands]]
name = "jupyterlab-jupytext"
category = "extensions"
command = '''
        nix develop .#jupyterlab-env --impure -c -- sudo -E jupyter labextension install "jupyterlab-jupytext"
        '''
help = "Install jupytext"
