[devshell]
packages = ["nixpkgs-fmt", "julia_16-bin"]
#startup.julia.text = "export JULIA_DEPOT_PATH"

[[commands]]
name = "pluto"
category = "Julia Package"
command = '''
        eval $(echo "nix develop --impure -c -- julia -e 'import Pkg; Pkg.activate(\"$DEVSHELL_ROOT/packages/julia\"); using Pluto; Pluto.run(host=\"$1\", port=$2)'")
        '''
help = "launch pluto server: pluto <ip> <port>"


[[commands]]
name = "jupyterWith-Env"
category = "jupyter"
command = "nix develop .#jupyterWith-env --impure -c -- jupyter-lab --ip $1 --port $2 --config $DEVSHELL_ROOT/jupyter_notebook_config.py"
help = "jupyterWith-Env <IP> <PORT>"

[[commands]]
name = "julia-wrapped"
category = "julia"
command = '''
        sed -i "s|/packages/julia/.*.|/packages/julia/$@\"\;|" nix/jupyterwith-env.nix
        nix develop .#jupyterWith-env --impure --command -- julia -L $DEVSHELL_ROOT/packages/julia/$@/startup.jl
        '''
help = "julia-wrapped <JuliaTutorial/default> | Initializing Julia Packages"


[[commands]]
name = "jupyterlab-jupytext"
category = "extensions"
command = '''
        nix develop .#jupyterWith-env --impure -c -- sudo -E jupyter labextension install "jupyterlab-jupytext"
        '''
help = "Install jupytext"
