[devshell]
packages = ["nixpkgs-fmt", "julia_16-bin"]
#startup.julia.text = "export JULIA_DEPOT_PATH"

[[commands]]
name = "pluto"
category = "Julia Package"
command = '''
        eval $(echo "nix develop --impure -c -- julia -L $DEVSHELL_ROOT/packages/julia/$1/startup.jl -e 'using Pluto; Pluto.run(host=\"$2\", port=$3)'")
        '''
help = "launch pluto server: pluto <juliaPackageDir> <ip> <port> | Example: pluto default 10.220.170.112 8889"


[[commands]]
name = "jupyterWith-Env"
category = "jupyter"
command = '''
        sed -i "s|/packages/julia/.*.|/packages/julia/$1\"\;|" nix/jupyterwith-env.nix
        nix develop .#jupyterWith-env --impure -c -- jupyter-lab --ip $2 --port $3 --config $DEVSHELL_ROOT/jupyter_notebook_config.py
'''
help = "jupyterWith-Env <juliaPackageDir> <IP> <PORT> | Example: jupyterWith-Env default 10.220.170.112 8888 "

[[commands]]
name = "julia-wrapped"
category = "julia"
command = '''
        sed -i "s|/packages/julia/.*.|/packages/julia/$@\"\;|" nix/jupyterwith-env.nix
        nix develop .#jupyterWith-env --impure --command -- julia -L $DEVSHELL_ROOT/packages/julia/$@/startup.jl
        '''
help = "julia-wrapped <JuliaTutorial/default> | Initializing Julia Packages"


[[commands]]
name = "jupyterlab-jupytext"
category = "extensions"
command = '''
        nix develop .#jupyterWith-env --impure -c -- sudo -E jupyter labextension install "jupyterlab-jupytext"
        '''
help = "Install jupytext"
