[devshell]
packages = ["nixpkgs-fmt", "julia_16-bin"]
startup.julia.text = "export JULIA_DEPOT_PATH=$DEVSHELL_ROOT/packages/julia/julia_depot"

[[commands]]
name = "pluto"
category = "Julia Package"
command = '''
        eval $(echo "julia -e 'import Pkg; Pkg.activate(\"$DEVSHELL_ROOT/packages/julia\"); using Pluto; Pluto.run(host=\"$1\", port=$2)'")
        '''
help = "launch pluto server: pluto <ip> <port>"


[[commands]]
name = "jupyterWith-Env"
category = "jupyter"
command = "nix develop .#jupyterWith-env --impure -c -- jupyter-lab --ip $1 --port $2 --config $DEVSHELL_ROOT/jupyter_notebook_config.py"
help = "jupyterWith-Env <IP> <PORT>"

[[commands]]
name = "julia-instantiate"
category = "julia"
command = '''
        eval $(echo "julia -e 'import Pkg; Pkg.activate(\"$DEVSHELL_ROOT/packages/julia\"); Pkg.instantiate()'")
        '''
help = "Instantiating Julia Packages"

[[commands]]
name = "julia-wrapped"
category = "julia"
command = '''
        cd $DEVSHELL_ROOT/packages/julia
        julia -L startup.jl
        '''
help = "Instantiating Julia Packages"


[[commands]]
name = "jupyterlab-jupytext"
category = "extensions"
command = '''
        nix develop .#jupyterWith-env --impure -c -- sudo -E jupyter labextension install "jupyterlab-jupytext"
        '''
help = "Install jupytext"
