name: "CI"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  nix-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
      with:
        fetch-depth: 0
    - uses: cachix/install-nix-action@v16
      with:
        install_url: https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.6.0pre20220113_a2811f8/install
    # Configure Nix to enable flakes
    - run: echo "experimental-features = nix-command flakes" | sudo tee -a /etc/nix/nix.conf

    - uses: cachix/cachix-action@v10
      with:
        name: gtrunsec
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - run: nix -Lv develop .#jupyterlab-ci --impure
