name: "Jupyter-data-science-environment"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Nix Flakes doesn't work on shallow clones
        fetch-depth: 0
    - uses: cachix/install-nix-action@v11
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-3.0pre20201007_5257a25/install
    # Configure Nix to enable flakes
    - run: echo "experimental-features = nix-command flakes" | sudo tee -a /etc/nix/nix.conf
    # using test-shell.nix
    - run: sh ./nix/action.sh
    - run: nix flake check --impure --show-trace
