name: "CI"
on:
  pull_request:
  push:
jobs:
  nix-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0
    - uses: cachix/install-nix-action@v13
      with:
        install_url:        https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210429_d15a196/install
    # Configure Nix to enable flakes
    - run: echo "experimental-features = nix-command flakes" | sudo tee -a /etc/nix/nix.conf
    # using test-shell.nix
    - run: sh ./nix/action.sh
    - run: nix flake check --impure --show-trace
