name: "CI"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  nix-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0
    - uses: cachix/install-nix-action@v13
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210604_8e6ee1b/install

    # Configure Nix to enable flakes
    - run: echo "experimental-features = nix-command flakes" | sudo tee -a /etc/nix/nix.conf

    - uses: cachix/cachix-action@v10
      with:
        name: gtrunsec
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - run: nix -Lv develop .#jupyterWith-ci --impure
